package http

import (
	stdhttp "net/http"

	"github.com/go-chi/chi/v5"
	chimiddleware "github.com/go-chi/chi/v5/middleware"

	appstate "omnidrive_cloud/internal/app"
	"omnidrive_cloud/internal/http/handlers"
	authmiddleware "omnidrive_cloud/internal/http/middleware"
)

func NewRouter(app *appstate.App) stdhttp.Handler {
	r := chi.NewRouter()
	r.Use(chimiddleware.RequestID)
	r.Use(chimiddleware.RealIP)
	r.Use(authmiddleware.RequestLogger(app.Logger))
	r.Use(chimiddleware.Recoverer)
	r.Use(authmiddleware.CORS(app.Config))

	healthHandler := handlers.NewHealthHandler(app)
	authHandler := handlers.NewAuthHandler(app)
	overviewHandler := handlers.NewOverviewHandler(app)
	deviceHandler := handlers.NewDeviceHandler(app)
	accountHandler := handlers.NewAccountHandler(app)
	materialHandler := handlers.NewMaterialHandler(app)
	skillHandler := handlers.NewSkillHandler(app)
	taskHandler := handlers.NewTaskHandler(app)
	aiHandler := handlers.NewAIHandler(app)
	billingHandler := handlers.NewBillingHandler(app)
	partnerHandler := handlers.NewPartnerHandler(app)
	agentHandler := handlers.NewAgentHandler(app)
	fileHandler := handlers.NewFileHandler(app)
	adminAuthHandler := handlers.NewAdminAuthHandler(app)
	adminRBACHandler := handlers.NewAdminRBACHandler(app)
	adminConsoleHandler := handlers.NewAdminConsoleHandler(app)
	adminFinanceHandler := handlers.NewAdminFinanceHandler(app)
	adminDistributionHandler := handlers.NewAdminDistributionHandler(app)
	adminWithdrawalHandler := handlers.NewAdminWithdrawalHandler(app)
	adminAIHandler := handlers.NewAdminAIHandler(app)
	adminSkillHandler := handlers.NewAdminSkillHandler(app)

	r.Get("/health", healthHandler.Health)
	r.Get("/ready", healthHandler.Ready)
	r.Get("/api/v1/files/*", fileHandler.Get)

	r.Route("/api/v1", func(api chi.Router) {
		api.Route("/auth", func(auth chi.Router) {
			auth.Post("/register", authHandler.Register)
			auth.Post("/login", authHandler.Login)
			auth.With(authmiddleware.RequireUser(app)).Get("/me", authHandler.Me)
		})

		api.Group(func(private chi.Router) {
			private.Use(authmiddleware.RequireUser(app))

			private.Route("/overview", func(overview chi.Router) {
				overview.Get("/summary", overviewHandler.Summary)
			})

			private.Get("/history", overviewHandler.History)

			private.Route("/devices", func(devices chi.Router) {
				devices.Get("/", deviceHandler.List)
				devices.Post("/claim", deviceHandler.Claim)
				devices.Get("/{deviceId}", deviceHandler.Detail)
				devices.Get("/{deviceId}/workspace", deviceHandler.Workspace)
				devices.Patch("/{deviceId}", deviceHandler.Update)
				devices.Post("/{deviceId}/unbind", deviceHandler.Unbind)
			})

			private.Route("/materials", func(materials chi.Router) {
				materials.Get("/roots", materialHandler.Roots)
				materials.Get("/list", materialHandler.List)
				materials.Get("/file", materialHandler.File)
				materials.Get("/workspace", materialHandler.Workspace)
			})

			private.Route("/accounts", func(accounts chi.Router) {
				accounts.Get("/", accountHandler.List)
				accounts.Get("/{accountId}", accountHandler.Detail)
				accounts.Get("/{accountId}/workspace", accountHandler.Workspace)
				accounts.Post("/{accountId}/skill-runs", accountHandler.CreateSkillRun)
				accounts.Delete("/{accountId}", accountHandler.Delete)
				accounts.Post("/{accountId}/validate", accountHandler.Validate)
				accounts.Post("/remote-login", accountHandler.CreateRemoteLogin)
				accounts.Get("/login-sessions/{sessionId}", accountHandler.GetLoginSession)
				accounts.Post("/login-sessions/{sessionId}/actions", accountHandler.CreateLoginAction)
			})

			private.Route("/skills", func(skills chi.Router) {
				skills.Get("/", skillHandler.List)
				skills.Post("/", skillHandler.Create)
				skills.Get("/{skillId}", skillHandler.Detail)
				skills.Get("/{skillId}/workspace", skillHandler.Workspace)
				skills.Get("/{skillId}/impact", skillHandler.Impact)
				skills.Patch("/{skillId}", skillHandler.Update)
				skills.Delete("/{skillId}", skillHandler.Delete)
				skills.Get("/{skillId}/assets", skillHandler.ListAssets)
				skills.Post("/{skillId}/assets", skillHandler.CreateAsset)
				skills.Delete("/{skillId}/assets/{assetId}", skillHandler.DeleteAsset)
				skills.Post("/{skillId}/upload", skillHandler.UploadAsset)
			})

			private.Route("/tasks", func(tasks chi.Router) {
				tasks.Get("/", taskHandler.List)
				tasks.Get("/diagnostics", taskHandler.Diagnostics)
				tasks.Post("/bulk-repair", taskHandler.BulkRepair)
				tasks.Post("/bulk-action", taskHandler.BulkAction)
				tasks.Post("/", taskHandler.Create)
				tasks.Get("/{taskId}", taskHandler.Detail)
				tasks.Get("/{taskId}/workspace", taskHandler.Workspace)
				tasks.Get("/{taskId}/events", taskHandler.Events)
				tasks.Get("/{taskId}/artifacts", taskHandler.Artifacts)
				tasks.Get("/{taskId}/materials", taskHandler.Materials)
				tasks.Post("/{taskId}/refresh-materials", taskHandler.RefreshMaterials)
				tasks.Post("/{taskId}/refresh-skill", taskHandler.RefreshSkill)
				tasks.Post("/{taskId}/cancel", taskHandler.Cancel)
				tasks.Post("/{taskId}/force-release", taskHandler.ForceRelease)
				tasks.Post("/{taskId}/resume", taskHandler.Resume)
				tasks.Post("/{taskId}/manual-resolve", taskHandler.ManualResolve)
				tasks.Post("/{taskId}/retry", taskHandler.Retry)
				tasks.Patch("/{taskId}", taskHandler.Update)
				tasks.Delete("/{taskId}", taskHandler.Delete)
			})

			private.Route("/ai", func(ai chi.Router) {
				ai.Get("/models", aiHandler.ListModels)
				ai.Get("/jobs", aiHandler.ListJobs)
				ai.Post("/chat/stream", aiHandler.StreamChat)
				ai.Post("/jobs", aiHandler.CreateJob)
				ai.Get("/jobs/{jobId}", aiHandler.DetailJob)
				ai.Get("/jobs/{jobId}/workspace", aiHandler.WorkspaceJob)
				ai.Get("/jobs/{jobId}/artifacts", aiHandler.ListArtifacts)
				ai.Post("/jobs/{jobId}/artifacts/upload", aiHandler.UploadArtifact)
				ai.Post("/jobs/{jobId}/publish-task", aiHandler.CreatePublishTask)
				ai.Patch("/jobs/{jobId}", aiHandler.UpdateJob)
				ai.Post("/jobs/{jobId}/cancel", aiHandler.CancelJob)
				ai.Post("/jobs/{jobId}/retry", aiHandler.RetryJob)
				ai.Post("/jobs/{jobId}/force-release", aiHandler.ForceReleaseJob)
			})

			private.Route("/billing", func(billing chi.Router) {
				billing.Get("/summary", billingHandler.Summary)
				billing.Get("/distribution/summary", billingHandler.DistributionSummary)
				billing.Get("/commissions", billingHandler.ListCommissions)
				billing.Get("/packages", billingHandler.ListPackages)
				billing.Get("/rules", billingHandler.ListPricingRules)
				billing.Get("/ledger", billingHandler.Ledger)
				billing.Get("/usage-events", billingHandler.ListUsageEvents)
				billing.Get("/orders", billingHandler.ListOrders)
				billing.Get("/withdrawals", billingHandler.ListWithdrawals)
				billing.Post("/withdrawals", billingHandler.CreateWithdrawal)
				billing.Get("/withdrawals/{withdrawalId}", billingHandler.DetailWithdrawal)
				billing.Post("/orders", billingHandler.CreateOrder)
				billing.Get("/orders/{orderId}", billingHandler.DetailOrder)
				billing.Get("/orders/{orderId}/events", billingHandler.ListOrderEvents)
				billing.Post("/orders/{orderId}/manual-submit", billingHandler.SubmitManualRecharge)
			})

			private.Route("/partners", func(partners chi.Router) {
				partners.Get("/me", partnerHandler.MyOverview)
				partners.Post("/me/open", partnerHandler.OpenMyProfile)
			})
		})

		api.Route("/agent", func(agent chi.Router) {
			agent.Post("/heartbeat", agentHandler.Heartbeat)
			agent.Get("/device-session/{deviceCode}", agentHandler.IssueDeviceSession)
			agent.Post("/accounts/sync", agentHandler.SyncAccount)
			agent.Get("/ai-jobs/{deviceCode}", agentHandler.ListAIJobs)
			agent.Post("/ai-jobs/sync", agentHandler.SyncAIJob)
			agent.Post("/ai-jobs/{jobId}/delivery", agentHandler.UpdateAIJobDelivery)
			agent.Get("/skills/{deviceCode}", agentHandler.ListSkills)
			agent.Post("/skills/sync", agentHandler.SyncSkillStates)
			agent.Post("/skills/retired-ack", agentHandler.AckRetiredSkills)
			agent.Post("/materials/roots/sync", materialHandler.SyncRoots)
			agent.Post("/materials/directory/sync", materialHandler.SyncDirectory)
			agent.Post("/materials/file/sync", materialHandler.SyncFile)
			agent.Get("/login-tasks/{deviceCode}", agentHandler.ListLoginTasks)
			agent.Post("/login-sessions/{sessionId}/event", agentHandler.PushLoginEvent)
			agent.Get("/login-sessions/{sessionId}/actions", agentHandler.ListLoginActions)
			agent.Get("/publish-tasks/{deviceCode}", agentHandler.ListPublishTasks)
			agent.Get("/publish-tasks/{taskId}/package", agentHandler.PublishTaskPackage)
			agent.Post("/publish-tasks/{taskId}/claim", agentHandler.ClaimPublishTask)
			agent.Post("/publish-tasks/{taskId}/renew", agentHandler.RenewPublishTaskLease)
			agent.Post("/publish-tasks/{taskId}/release", agentHandler.ReleasePublishTaskLease)
			agent.Post("/publish-tasks/sync", agentHandler.SyncPublishTask)
		})
	})

	r.Route("/api/admin/v1", func(admin chi.Router) {
		admin.Route("/auth", func(auth chi.Router) {
			auth.Post("/login", adminAuthHandler.Login)
		})

		admin.Group(func(private chi.Router) {
			private.Use(authmiddleware.RequireAdmin(app))

			private.Post("/auth/logout", adminAuthHandler.Logout)
			private.Get("/me", adminAuthHandler.Me)
			private.With(authmiddleware.RequireAdminPermission("admin.manage")).Get("/admins", adminRBACHandler.ListAdmins)
			private.With(authmiddleware.RequireAdminPermission("admin.manage")).Post("/admins", adminRBACHandler.CreateAdmin)
			private.With(authmiddleware.RequireAdminPermission("admin.manage")).Patch("/admins/{adminId}", adminRBACHandler.UpdateAdmin)
			private.With(authmiddleware.RequireAdminPermission("admin.manage")).Get("/roles", adminRBACHandler.ListRoles)
			private.With(authmiddleware.RequireAdminPermission("admin.manage")).Post("/roles", adminRBACHandler.CreateRole)
			private.With(authmiddleware.RequireAdminPermission("system.config")).Get("/system-config", adminAuthHandler.SystemConfig)
			private.With(authmiddleware.RequireAdminPermission("system.config")).Patch("/system-config", adminAuthHandler.UpdateSystemConfig)
			private.With(authmiddleware.RequireAdminPermission("system.config")).Post("/system-config/storyboard-assets", adminAuthHandler.UploadStoryboardAsset)

			private.With(authmiddleware.RequireAdminPermission("admin.manage")).Get("/dashboard/summary", adminConsoleHandler.DashboardSummary)
			private.With(authmiddleware.RequireAdminPermission("user.read")).Get("/users", adminConsoleHandler.ListUsers)
			private.With(authmiddleware.RequireAdminPermission("user.update")).Post("/users/bulk-action", adminConsoleHandler.BulkActionUsers)
			private.With(authmiddleware.RequireAdminPermission("user.read")).Get("/users/{userId}", adminConsoleHandler.DetailUser)
			private.With(authmiddleware.RequireAdminPermission("user.read")).Get("/users/{userId}/workspace", adminConsoleHandler.UserWorkspace)
			private.With(authmiddleware.RequireAdminPermission("user.update")).Patch("/users/{userId}", adminConsoleHandler.UpdateUser)
			private.With(authmiddleware.RequireAdminPermission("device.read")).Get("/devices", adminConsoleHandler.ListDevices)
			private.With(authmiddleware.RequireAdminPermission("device.update")).Post("/devices/bulk-action", adminConsoleHandler.BulkActionDevices)
			private.With(authmiddleware.RequireAdminPermission("device.read")).Get("/devices/{deviceId}", adminConsoleHandler.DetailDevice)
			private.With(authmiddleware.RequireAdminPermission("device.read")).Get("/devices/{deviceId}/workspace", adminConsoleHandler.DeviceWorkspace)
			private.With(authmiddleware.RequireAdminPermission("device.update")).Patch("/devices/{deviceId}", adminConsoleHandler.UpdateDevice)
			private.With(authmiddleware.RequireAdminPermission("device.update")).Post("/devices/{deviceId}/force-release", adminConsoleHandler.ForceReleaseDevice)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/media-accounts", adminConsoleHandler.ListMediaAccounts)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/media-accounts/bulk-action", adminConsoleHandler.BulkActionMediaAccounts)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/media-accounts/remote-login", adminConsoleHandler.CreateRemoteLogin)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/media-accounts/{accountId}", adminConsoleHandler.DetailMediaAccount)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Patch("/media-accounts/{accountId}", adminConsoleHandler.UpdateMediaAccount)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/media-accounts/{accountId}/workspace", adminConsoleHandler.MediaAccountWorkspace)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/media-accounts/{accountId}/validate", adminConsoleHandler.ValidateMediaAccount)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Delete("/media-accounts/{accountId}", adminConsoleHandler.DeleteMediaAccount)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/accounts", adminConsoleHandler.ListMediaAccounts)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/accounts/bulk-action", adminConsoleHandler.BulkActionMediaAccounts)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/accounts/remote-login", adminConsoleHandler.CreateRemoteLogin)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/accounts/{accountId}", adminConsoleHandler.DetailMediaAccount)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Patch("/accounts/{accountId}", adminConsoleHandler.UpdateMediaAccount)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/accounts/{accountId}/workspace", adminConsoleHandler.MediaAccountWorkspace)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/accounts/{accountId}/validate", adminConsoleHandler.ValidateMediaAccount)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Delete("/accounts/{accountId}", adminConsoleHandler.DeleteMediaAccount)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/login-sessions/{sessionId}", adminConsoleHandler.GetLoginSession)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/login-sessions/{sessionId}/actions", adminConsoleHandler.CreateLoginSessionAction)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/publish-tasks", adminConsoleHandler.ListPublishTasks)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/publish-tasks/bulk-action", adminConsoleHandler.BulkActionPublishTasks)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/publish-tasks/{taskId}", adminConsoleHandler.DetailPublishTask)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Patch("/publish-tasks/{taskId}", adminConsoleHandler.UpdatePublishTask)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/publish-tasks/{taskId}/workspace", adminConsoleHandler.PublishTaskWorkspace)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/publish-tasks/{taskId}/events", adminConsoleHandler.ListPublishTaskEvents)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/publish-tasks/{taskId}/artifacts", adminConsoleHandler.ListPublishTaskArtifacts)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/publish-tasks/{taskId}/materials", adminConsoleHandler.ListPublishTaskMaterials)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/publish-tasks/{taskId}/cancel", adminConsoleHandler.CancelPublishTask)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/publish-tasks/{taskId}/retry", adminConsoleHandler.RetryPublishTask)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/publish-tasks/{taskId}/force-release", adminConsoleHandler.ForceReleasePublishTask)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/publish-tasks/{taskId}/resume", adminConsoleHandler.ResumePublishTask)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/publish-tasks/{taskId}/manual-resolve", adminConsoleHandler.ManualResolvePublishTask)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/ai-jobs", adminConsoleHandler.ListAIJobs)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/ai-jobs/bulk-action", adminConsoleHandler.BulkActionAIJobs)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/ai-jobs/{jobId}", adminConsoleHandler.DetailAIJob)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Patch("/ai-jobs/{jobId}", adminConsoleHandler.UpdateAIJob)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/ai-jobs/{jobId}/workspace", adminConsoleHandler.AIJobWorkspace)
			private.With(authmiddleware.RequireAdminPermission("task.read")).Get("/ai-jobs/{jobId}/artifacts", adminConsoleHandler.ListAIJobArtifacts)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/ai-jobs/{jobId}/cancel", adminConsoleHandler.CancelAIJob)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/ai-jobs/{jobId}/retry", adminConsoleHandler.RetryAIJob)
			private.With(authmiddleware.RequireAdminPermission("task.operate")).Post("/ai-jobs/{jobId}/force-release", adminConsoleHandler.ForceReleaseAIJob)
			private.With(authmiddleware.RequireAdminPermission("finance.read")).Get("/pricing/packages", adminConsoleHandler.ListPricingPackages)
			private.With(authmiddleware.RequireAdminPermission("finance.read")).Get("/pricing/rules", adminConsoleHandler.ListPricingRules)
			private.With(authmiddleware.RequireAdminPermission("finance.adjust")).Post("/pricing/packages", adminFinanceHandler.CreatePricingPackage)
			private.With(authmiddleware.RequireAdminPermission("finance.adjust")).Patch("/pricing/packages/{packageId}", adminFinanceHandler.UpdatePricingPackage)
			private.With(authmiddleware.RequireAdminPermission("finance.read")).Get("/orders", adminConsoleHandler.ListOrders)
			private.With(authmiddleware.RequireAdminPermission("finance.read")).Get("/orders/{orderId}", adminFinanceHandler.DetailOrder)
			private.With(authmiddleware.RequireAdminPermission("finance.read")).Get("/orders/{orderId}/events", adminFinanceHandler.ListOrderEvents)
			private.With(authmiddleware.RequireAdminPermission("finance.read")).Get("/wallet-ledgers", adminConsoleHandler.ListWalletLedgers)
			private.With(authmiddleware.RequireAdminPermission("finance.read")).Get("/wallet-ledgers/{ledgerId}", adminFinanceHandler.DetailWalletLedger)
			private.With(authmiddleware.RequireAdminPermission("finance.read")).Get("/usage-events", adminConsoleHandler.ListUsageEvents)
			private.With(authmiddleware.RequireAdminPermission("finance.adjust")).Post("/wallet-adjustments", adminFinanceHandler.CreateWalletAdjustment)
			private.With(authmiddleware.RequireAdminPermission("support_recharge.review")).Get("/support-recharges", adminConsoleHandler.ListSupportRecharges)
			private.With(authmiddleware.RequireAdminPermission("support_recharge.review")).Get("/support-recharges/{orderId}", adminConsoleHandler.DetailSupportRecharge)
			private.With(authmiddleware.RequireAdminPermission("support_recharge.review")).Get("/support-recharges/{orderId}/events", adminConsoleHandler.ListSupportRechargeEvents)
			private.With(authmiddleware.RequireAdminPermission("support_recharge.review")).Post("/support-recharges/{orderId}/credit", adminConsoleHandler.CreditSupportRecharge)
			private.With(authmiddleware.RequireAdminPermission("support_recharge.review")).Post("/support-recharges/{orderId}/reject", adminConsoleHandler.RejectSupportRecharge)
			private.With(authmiddleware.RequireAdminPermission("distribution.read")).Get("/distribution/partners", adminDistributionHandler.ListPartners)
			private.With(authmiddleware.RequireAdminPermission("distribution.settle")).Post("/distribution/partners", adminDistributionHandler.OpenPartner)
			private.With(authmiddleware.RequireAdminPermission("distribution.read")).Get("/distribution/relations", adminDistributionHandler.ListRelations)
			private.With(authmiddleware.RequireAdminPermission("distribution.settle")).Post("/distribution/relations", adminDistributionHandler.CreateRelation)
			private.With(authmiddleware.RequireAdminPermission("distribution.read")).Get("/distribution/rules", adminDistributionHandler.ListRules)
			private.With(authmiddleware.RequireAdminPermission("distribution.settle")).Post("/distribution/rules", adminDistributionHandler.CreateRule)
			private.With(authmiddleware.RequireAdminPermission("distribution.read")).Get("/distribution/commissions", adminDistributionHandler.ListCommissions)
			private.With(authmiddleware.RequireAdminPermission("distribution.read")).Get("/distribution/settlements", adminDistributionHandler.ListSettlements)
			private.With(authmiddleware.RequireAdminPermission("distribution.settle")).Post("/distribution/settlements", adminDistributionHandler.CreateSettlement)
			private.With(authmiddleware.RequireAdminPermission("withdrawal.review")).Get("/withdrawals", adminWithdrawalHandler.ListWithdrawals)
			private.With(authmiddleware.RequireAdminPermission("withdrawal.review")).Get("/withdrawals/{withdrawalId}", adminWithdrawalHandler.DetailWithdrawal)
			private.With(authmiddleware.RequireAdminPermission("withdrawal.review")).Post("/withdrawals/{withdrawalId}/approve", adminWithdrawalHandler.ApproveWithdrawal)
			private.With(authmiddleware.RequireAdminPermission("withdrawal.review")).Post("/withdrawals/{withdrawalId}/reject", adminWithdrawalHandler.RejectWithdrawal)
			private.With(authmiddleware.RequireAdminPermission("withdrawal.review")).Post("/withdrawals/{withdrawalId}/mark-paid", adminWithdrawalHandler.MarkWithdrawalPaid)
			private.With(authmiddleware.RequireAdminPermission("admin.manage")).Get("/audits", adminConsoleHandler.ListAudits)

			private.With(authmiddleware.RequireAdminPermission("ai.read")).Get("/ai/models", adminAIHandler.ListModels)
			private.With(authmiddleware.RequireAdminPermission("ai.read")).Get("/ai/models/{modelId}", adminAIHandler.DetailModel)
			private.With(authmiddleware.RequireAdminPermission("ai.update")).Post("/ai/models", adminAIHandler.CreateModel)
			private.With(authmiddleware.RequireAdminPermission("ai.update")).Patch("/ai/models/{modelId}", adminAIHandler.UpdateModel)
			private.With(authmiddleware.RequireAdminPermission("ai.update")).Delete("/ai/models/{modelId}", adminAIHandler.DeleteModel)

			private.With(authmiddleware.RequireAdminPermission("skill.read")).Get("/skills", adminSkillHandler.ListSkills)
			private.With(authmiddleware.RequireAdminPermission("skill.update")).Patch("/skills/{skillId}", adminSkillHandler.UpdateSkill)
		})
	})

	return r
}
