from pathlib import Path

BASE_DIR = Path(__file__).parent.resolve()

LOCAL_CHROME_PATH = "/usr/bin/google-chrome"
LOCAL_CHROME_HEADLESS = False
SAU_LOG_LEVEL = "INFO"

OMNIDRIVE_AGENT_ENABLED = True
OMNIDRIVE_BASE_URL = "https://omnidrive.example.com"
OMNIDRIVE_AGENT_KEY = ""
OMNIDRIVE_AGENT_POLL_INTERVAL = 5
OMNIDRIVE_AGENT_HEARTBEAT_INTERVAL = 30
OMNIDRIVE_ACCOUNT_SYNC_INTERVAL = 60
OMNIDRIVE_ACCOUNT_VALIDATION_INTERVAL = 21600
OMNIDRIVE_MATERIAL_SYNC_INTERVAL = 300
OMNIDRIVE_SKILL_SYNC_INTERVAL = 120
OMNIDRIVE_PUBLISH_SYNC_INTERVAL = 5
OMNIDRIVE_MATERIAL_SYNC_MAX_FILES = 1000

OMNIBULL_DEVICE_IDENTITY_FILE = "/etc/omnibull/device.json"

OMNIBULL_PUBLISH_WORKERS = 1
OMNIBULL_PUBLISH_DISPATCH_INTERVAL_SECONDS = 5
OMNIBULL_TASK_RETENTION_DAYS = 7
OMNIBULL_API_KEY = ""

OMNIBULL_CORS_ALLOWED_ORIGINS = "https://omnidrive.example.com,https://admin.example.com"
OMNIBULL_CORS_ALLOWED_METHODS = "GET,POST,PUT,PATCH,DELETE,OPTIONS"
OMNIBULL_CORS_ALLOWED_HEADERS = "Authorization,Content-Type,X-Requested-With,X-Omnibull-Key"
OMNIBULL_CORS_EXPOSE_HEADERS = "Content-Disposition,X-Accel-Buffering"
OMNIBULL_CORS_ALLOW_CREDENTIALS = False
OMNIBULL_CORS_MAX_AGE = 86400

OMNIBULL_MATERIAL_ROOTS = {
    "localWorkspace": "/data/omnibull/workspace",
}
