param(
    [string]$EnvFile = "",
    [switch]$InstallChrome = $true,
    [switch]$InstallTask = $true
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = [System.IO.Path]::GetFullPath((Join-Path $ScriptDir ".."))

if ([string]::IsNullOrWhiteSpace($EnvFile)) {
    $EnvFile = Join-Path $RootDir "deploy\env\omnibull.windows.env"
}

function Write-Log {
    param([string]$Message)
    "[{0}] [bootstrap] {1}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Message
}

function Assert-Command {
    param([string]$Name)
    $command = Get-Command $Name -ErrorAction SilentlyContinue
    if ($null -eq $command) {
        throw ("Required command not found: {0}" -f $Name)
    }
    return $command.Source
}

function Ensure-WingetPackage {
    param(
        [string]$PackageId,
        [string]$DisplayName
    )

    Write-Log ("Ensuring {0} ({1}) is installed" -f $DisplayName, $PackageId)
    & winget install --exact --id $PackageId --accept-package-agreements --accept-source-agreements --silent *> $null
}

function Resolve-PythonPath {
    foreach ($candidate in @(
        (Join-Path $RootDir ".venv\Scripts\python.exe"),
        (Join-Path $RootDir "venv\Scripts\python.exe"),
        (Join-Path $env:LOCALAPPDATA "Programs\Python\Python311\python.exe"),
        (Join-Path $env:LOCALAPPDATA "Programs\Python\Python312\python.exe"),
        "$env:ProgramFiles\Python311\python.exe",
        "$env:ProgramFiles\Python312\python.exe"
    )) {
        if (Test-Path -LiteralPath $candidate) {
            return $candidate
        }
    }

    foreach ($name in @("python.exe", "python")) {
        $command = Get-Command $name -ErrorAction SilentlyContinue
        if ($null -ne $command) {
            return $command.Source
        }
    }

    $pyCommand = Get-Command "py.exe" -ErrorAction SilentlyContinue
    if ($null -ne $pyCommand) {
        return $pyCommand.Source
    }

    throw "Python runtime could not be resolved after bootstrap."
}

function Resolve-NpmPath {
    foreach ($candidate in @(
        "$env:ProgramFiles\nodejs\npm.cmd",
        "${env:ProgramFiles(x86)}\nodejs\npm.cmd"
    )) {
        if (-not [string]::IsNullOrWhiteSpace($candidate) -and (Test-Path -LiteralPath $candidate)) {
            return $candidate
        }
    }

    foreach ($name in @("npm.cmd", "npm")) {
        $command = Get-Command $name -ErrorAction SilentlyContinue
        if ($null -ne $command) {
            return $command.Source
        }
    }

    throw "npm could not be resolved after bootstrap."
}

function Ensure-ExecutableDirOnPath {
    param([string]$ExecutablePath)

    if ([string]::IsNullOrWhiteSpace($ExecutablePath)) {
        return
    }

    $directory = Split-Path -Parent $ExecutablePath
    if ([string]::IsNullOrWhiteSpace($directory)) {
        return
    }

    $segments = @($env:Path -split ';' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    if ($segments -contains $directory) {
        return
    }

    $env:Path = "{0};{1}" -f $directory, ($segments -join ';')
}

function Write-WindowsEnvFile {
    param(
        [string]$Path,
        [string]$PythonPath,
        [string]$NpmPath,
        [string]$PlaywrightBrowsersPath
    )

    $lines = @(
        "# Generated by sau_windows_bootstrap.ps1",
        "PYTHONUNBUFFERED=1",
        ("SAU_PYTHON_BIN={0}" -f $PythonPath),
        ("SAU_NPM_BIN={0}" -f $NpmPath),
        "SAU_BACKEND_PORT=5409",
        "SAU_FRONTEND_HOST=0.0.0.0",
        "SAU_FRONTEND_PORT=5173",
        "SAU_FRONTEND_MODE=preview",
        "SAU_FRONTEND_BUILD_ON_START=auto",
        "SAU_FRONTEND_INSTALL_ON_START=1",
        ("PLAYWRIGHT_BROWSERS_PATH={0}" -f $PlaywrightBrowsersPath),
        ("SAU_RUNTIME_DIR={0}" -f (Join-Path $RootDir "runtime")),
        ("SAU_LOG_DIR={0}" -f (Join-Path $RootDir "logs"))
    )
    Set-Content -LiteralPath $Path -Value $lines -Encoding ASCII
}

Assert-Command -Name "winget" | Out-Null

New-Item -ItemType Directory -Path (Join-Path $RootDir "logs") -Force | Out-Null

Ensure-WingetPackage -PackageId "Python.Python.3.11" -DisplayName "Python 3.11"
Ensure-WingetPackage -PackageId "OpenJS.NodeJS.LTS" -DisplayName "Node.js LTS"
if ($InstallChrome) {
    Ensure-WingetPackage -PackageId "Google.Chrome" -DisplayName "Google Chrome"
}

$pythonPath = Resolve-PythonPath
$npmPath = Resolve-NpmPath
$playwrightBrowsersPath = if ($env:PLAYWRIGHT_BROWSERS_PATH) {
    $env:PLAYWRIGHT_BROWSERS_PATH
}
else {
    Join-Path ([System.IO.Path]::GetFullPath((Join-Path $RootDir ".."))) "ms-playwright"
}
Ensure-ExecutableDirOnPath -ExecutablePath $pythonPath
Ensure-ExecutableDirOnPath -ExecutablePath $npmPath
New-Item -ItemType Directory -Path $playwrightBrowsersPath -Force | Out-Null
$env:PLAYWRIGHT_BROWSERS_PATH = $playwrightBrowsersPath

if (-not (Test-Path -LiteralPath (Join-Path $RootDir ".venv\Scripts\python.exe"))) {
    Write-Log "Creating Python virtual environment"
    if ([System.IO.Path]::GetFileName($pythonPath).ToLowerInvariant() -eq "py.exe") {
        & $pythonPath -3 -m venv (Join-Path $RootDir ".venv")
    }
    else {
        & $pythonPath -m venv (Join-Path $RootDir ".venv")
    }
}

$venvPython = Join-Path $RootDir ".venv\Scripts\python.exe"
if (-not (Test-Path -LiteralPath $venvPython)) {
    throw "Expected virtual environment python was not created."
}

Write-Log "Installing Python dependencies"
$requirementsPath = Join-Path $RootDir "requirements.windows.txt"
Get-Content -LiteralPath (Join-Path $RootDir "requirements.txt") | Set-Content -LiteralPath $requirementsPath -Encoding UTF8
$pipUpgradeArgs = @("-m", "pip", "install", "--upgrade", "pip")
$pipInstallArgs = @("-m", "pip", "install", "-r", $requirementsPath)
if ($env:SAU_PIP_INDEX_URL) {
    $pipUpgradeArgs += @("-i", $env:SAU_PIP_INDEX_URL)
    $pipInstallArgs += @("-i", $env:SAU_PIP_INDEX_URL)
}
if ($env:SAU_PIP_TRUSTED_HOST) {
    $pipUpgradeArgs += @("--trusted-host", $env:SAU_PIP_TRUSTED_HOST)
    $pipInstallArgs += @("--trusted-host", $env:SAU_PIP_TRUSTED_HOST)
}
& $venvPython @pipUpgradeArgs *>> (Join-Path $RootDir "logs\windows_bootstrap.log")
& $venvPython @pipInstallArgs *>> (Join-Path $RootDir "logs\windows_bootstrap.log")

Write-Log "Installing Playwright Chromium"
if ($env:SAU_PLAYWRIGHT_DOWNLOAD_HOST) {
    $env:PLAYWRIGHT_DOWNLOAD_HOST = $env:SAU_PLAYWRIGHT_DOWNLOAD_HOST
}
& $venvPython -m playwright install chromium *>> (Join-Path $RootDir "logs\windows_bootstrap.log")

Write-Log "Installing sau_frontend dependencies"
Push-Location (Join-Path $RootDir "sau_frontend")
try {
    if ($env:SAU_NPM_REGISTRY) {
        & $npmPath config set registry $env:SAU_NPM_REGISTRY *>> (Join-Path $RootDir "logs\windows_bootstrap.log")
    }
    if (Test-Path -LiteralPath "package-lock.json") {
        & $npmPath ci *>> (Join-Path $RootDir "logs\windows_bootstrap.log")
    }
    else {
        & $npmPath install *>> (Join-Path $RootDir "logs\windows_bootstrap.log")
    }
    Write-Log "Building sau_frontend"
    & $npmPath run build *>> (Join-Path $RootDir "logs\windows_bootstrap.log")
}
finally {
    Pop-Location
}

$envDir = Split-Path -Parent $EnvFile
if (-not (Test-Path -LiteralPath $envDir)) {
    New-Item -ItemType Directory -Path $envDir -Force | Out-Null
}
if (-not (Test-Path -LiteralPath $EnvFile)) {
    Write-WindowsEnvFile -Path $EnvFile -PythonPath $venvPython -NpmPath $npmPath -PlaywrightBrowsersPath $playwrightBrowsersPath
    Write-Log ("Created environment file: {0}" -f $EnvFile)
}

if ($InstallTask) {
    Write-Log "Installing Windows logon task for SAU"
    & (Get-Command "powershell.exe" -ErrorAction Stop).Source -NoProfile -ExecutionPolicy Bypass -File (Join-Path $ScriptDir "sau_windows.ps1") install-task -EnvFile $EnvFile
}

Write-Log "Windows SAU bootstrap completed."
